# Generated by Django 4.2.10 on 2024-03-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('RegionID', models.AutoField(primary_key=True, serialize=False)),
                ('RegionName', models.CharField(max_length=250)),
            ],
        ),
    ]
